name: Deploy to Pages

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Pages
    uses: bigbang1112/workflows/.github/workflows/deploy-pages.yml@main
    with:
      dotnet-version: 10.x.x
      workloads: wasm-tools
      project: Samples/Overview