name: Publish NuGet

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write # important for release description edit and asset upload
  packages: write

jobs:
  deploy:
    name: Publish NuGet
    uses: bigbang1112/workflows/.github/workflows/publish-nuget.yml@main
    with:
      dotnet-version: 10.x.x
      project-path: Src/*
      pack-path: "{Src/*,Templates}"
      enable-tests: false
      enable-coverage: false
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}